# Generated by Django 5.2.6 on 2024-10-01 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0015_alter_for_big_int'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='picker/logos'),
        ),
        migrations.AlterField(
            model_name='pickerfavorite',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickermembership',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickset',
            name='strategy',
            field=models.CharField(choices=[('PICK', 'Picker'), ('RAND', 'Random'), ('HOME', 'Home Team'), ('BEST', 'Best Record')], default='PICK', max_length=4),
        ),
        migrations.AlterField(
            model_name='pickset',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='picker/logos'),
        ),
        migrations.CreateModel(
            name='Picker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pickset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pickerfavorite',
            name='picker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picker_favorites', to='picker.picker'),
        ),
        migrations.AddField(
            model_name='pickermembership',
            name='picker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picker_memberships', to='picker.picker'),
        ),
        migrations.AddField(
            model_name='pickset',
            name='picker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picksets', to='picker.picker'),
        ),
        migrations.AlterUniqueTogether(
            name='pickset',
            unique_together={('picker', 'gameset')},
        ),
    ]
