# Generated by Django 5.2.4 on 2025-11-26 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("picker", "0016_picker"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"base_manager_name": "objects", "ordering": ("name",)},
        ),
        migrations.RemoveField(
            model_name="pickerfavorite",
            name="user",
        ),
        migrations.RemoveField(
            model_name="pickermembership",
            name="user",
        ),
        migrations.RemoveField(
            model_name="pickset",
            name="user",
        ),
        migrations.DeleteModel(
            name="Preference",
        ),
    ]
